language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: false
install:
  - pip install python==2.7
  - pip install scikit-bio==0.2.3
  - pip install numpy
  - pip install scipy
script:
  - bash ./build.sh
  - cd tests; python test_sortmerna.py
