language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
sudo: false
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - wget http://bioinfo.lifl.fr/RNA/sortmerna/material/data.tar.gz
  - tar -zxvf data.tar.gz
  - mv data ./tests/
install:
  - conda create --yes -n env_name python=2.7 numpy scipy
  - source activate env_name
script:
  - bash ./build.sh
  - cd tests; python test_sortmerna.py
