#
# FILE: build.yaml
# Created: Oct 18, 2019 Fri
#
# Build configuration used by build.py
#
com:
  windows:
    cmake_gen: Visual Studio 16 2019
  linux:
    cmake_gen: Unix Makefiles
  osx:
    cmake_gen: Unix Makefiles

sortmerna:
  url: https://github.com/biocore/sortmerna.git
  build_type: release
  package_type: t1
  windows:
    src:     C:\Users\ak\a01_code\sortmerna
    dirent_src:  C:\Users\ak\a01_libs\dirent
  wsl:
    cmake_gen: Unix Makefiles
  linux:
    cmake_gen: Unix Makefiles
  osx:
    cmake_gen: Unix Makefiles

rocksdb:
  url: https://github.com/facebook/rocksdb.git
  build_type: release
  package_type: t1
  windows:
    src: C:\Users\ak\a01_libs\rocksdb # sources location
    link_types:
      t1:
        WITH_MD_LIBRARY: 1
        WITH_XPRESS: 1
        WITH_ZLIB: 1
      t2:
        WITH_MD_LIBRARY: 1
        WITH_XPRESS: 1
        WITH_ZLIB: 1
      t3:  # default
        WITH_MD_LIBRARY: 1
        WITH_XPRESS: 1
        WITH_ZLIB: 1
        ZLIB_LIB_DEBUG: zlibstaticd.lib
        ZLIB_LIB_RELEASE: zlibstatic.lib
        PORTABLE: 0
        OPTDBG: 0
        WITH_RUNTIME_DEBUG: 0
        WITH_TESTS: 0
        WITH_TOOLS: 0

# only used on Windows
dirent:
  url: https://github.com/tronkko/dirent
  src: C:\Users\ak\a01_libs\dirent

zlib:
  url: https://github.com/madler/zlib.git
  windows:
    src:    C:\Users\ak\a01_libs\zlib
    link_types:
      t1:
        type: MD/MDd # multi-threaded DLL runtime lib (default)
        dir: t1 # added to the distribution location path i.e. $ZLIB_SRC/dist/t1/
      t2:
        type: MT/MTd # mutli-threaded Static runtime lib. Needs either CMakeLists modification, or command line options.
        dir: t2
  linux:
    src:  /media/a01_libs/zlib

rapidjson:
  url: https://github.com/Tencent/rapidjson

cmake:
  url: https://github.com/Kitware/CMake/releases/download/v{}/cmake-{}-Linux-x86_64.tar.gz
  ver: 3.15.3

conda:
  url: 'http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
